baseURL = "http://satpreetsingh.github.io/"
languageCode = "en-us"
title = "Satpreet H. Singh"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "GTM-TZ6DFVX"  # add your tracking id

[params]
  author = "Satpreet H. Singh"
  description = "Satpreet's Homepage"
  [params.footer]
    text = "Hugo : Researcher"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "850px"
    avatarSize = "120px"
    colorBlack = "#222222"
    colorRed = "#dc3545"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "Research"
    url = "/research"
  [[menu.main]]
    name = "Resume/CV"
    url = "https://drive.google.com/file/d/1PEkjFtd7cKtlXX8Uy4PbezBIub0JuNRt/view?usp=share_link"
  [[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/tweetsatpreet"
  [[menu.main]]
    name = "Service"
    url = "/service"
    

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

